apiVersion: miro.onesource.pt/v1
kind: Component
metadata:
  name: nginx-component
  namespace: test-app
spec:
  application: test-app
  # 1.21.5
  image: nginx:1.21.5
  name: nginx-component
  # replicas: 1
  expose:
    - is-public: true
      is-peered: true
      is-exposing-metrics: false
      containerPort: 80
      clusterPort: 4000
