---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  image: quay.io/prometheus/alertmanager:v0.23.0
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: thanos
  alertmanagerConfigNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.21.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-main
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9094
      targetPort: web
  selector:
    alertmanager: main
    app: alertmanager
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-main
  namespace: monitoring
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-alert-manager
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: alert-manager.monitoring.onesource.pt
      http:
        paths:
          - backend:
              service:
                name: alertmanager-operated
                port:
                  number: 9093
            path: /
            pathType: ImplementationSpecific
