apiVersion: v1
kind: Secret
metadata:
  name: thanosruler-alertmanager-config
  namespace: monitoring
stringData:
  alertmanager-configs.yaml: |-
    alertmanagers:
    - static_configs:
      - "alertmanager-operated.monitoring.svc.cluster.local:9093"
      api_version: v2
