apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: components.miro.onesource.pt
spec:
  scope: Namespaced
  group: miro.onesource.pt
  names:
    kind: Component
    plural: components
    singular: component
    shortNames:
      - comp
      - comps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - application
                - image
              properties:
                name:
                  type: string
                  maxLength: 63
                application:
                  type: string
                  maxLength: 63
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                expose:
                  type: array
                  items:
                    type: object
                    required:
                      - is-public
                      - is-exposing-metrics
                      - is-peered
                      - containerPort
                      - clusterPort
                    properties:
                      is-public:
                        type: boolean
                      is-peered:
                        type: boolean
                      is-exposing-metrics:
                        type: boolean
                      containerPort:
                        type: integer
                        minimum: 0
                        maximum: 65535
                      clusterPort:
                        type: integer
                        minimum: 0
                        maximum: 65535
                env:
                  type: object
                  properties:
                    is-secret:
                      type: boolean
                    variables:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                tls:
                  type: object
                  properties:
                    name:
                      type: string

            # ************************ Status ************************#
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

      additionalPrinterColumns:
        - name: Current status # Rrunning, pending, Failed
          type: string
          priority: 0
          jsonPath: .status.component_watch.current_status
        - name: Details
          type: string
          priority: 0
          jsonPath: .status.component_watch.details # If status is Running, No details to provide
