apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customclusters.miro.onesource.pt
spec:
  scope: Namespaced
  group: miro.onesource.pt
  names:
    kind: CustomCluster
    plural: customclusters
    singular: customcluster
    shortNames:
    - cc
  versions:
    - name: v1
      served: true
      storage: true
      subresources: { status: { } }
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                configMapRef:
                  type: object
                  properties:
                    name:
                      type: string
                infra-provider:
                  type: string
                bootstrap-provider:
                  type: string
                flavor:
                  type: string
                name:
                  type: string
                kubernetes-version:
                  type: string
                control-plane-count:
                  type: integer
                control-plane-flavor:
                  type: string
                worker-machine-count:
                  type: integer
                worker-machine-flavor:
                  type: string
                image:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Control Plane Ready
          type: boolean
          description: "status of Control Plane"
          jsonPath: .status.control-plane-ready
        - name: Infrastructure Ready
          type: boolean
          description: "status of the Infrastructure"
          jsonPath: .status.infrastructure-ready
        - name: Phase
          type: string
          description: "cluster provisioning phase: pending, provisioned"
          jsonPath: .status.phase
        - name: Monitoring Ready
          type: boolean
          description: "status of the automatically installed monitoring components"
          jsonPath: .status.monitoring-ready
        - name: Liqo Ready
          type: boolean
          description: "status of the automatically installed liqo components"
          jsonPath: .status.liqo-ready