apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    app: {{name}}
    service: {{name}}
spec:
  ports:
  {% for exp in expose %}
  - protocol: TCP
    name: {{ name ~ "-" ~ exp.clusterPort }}
    port: {{ exp.clusterPort }}
    targetPort: {{ exp.containerPort }}
  {% endfor %}
  selector:
    app: {{name}}
