apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-error
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: invalid-image-name:latest  # Intentionally invalid image name
        ports:
        - containerPort: 80
